import './globals.css';
import type { Metadata } from 'next';
import { config } from '@fortawesome/fontawesome-svg-core';
import { ReduxProvider } from '@/components/provider/ReduxProvider';
config.autoAddCss = false;

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ReduxProvider>
            <html lang="ko">
                <body>
                    <main className="bg-default w-full h-full flex flex-col justify-center items-center overflow-hidden">
                        <div className="container-box h-full">{children}</div>
                    </main>
                </body>
            </html>
        </ReduxProvider>
    );
}
